#!/usr/bin/env python3
"""Generate the sph.input reference page from parallel_bleeding_edge/src/init.f.

The namelist members, their default values and the explanatory comments all
come straight from the source, so this page cannot drift from the code.  Run
    python3 docs/generate_reference.py
from the top of the repository after changing init.f.
"""
import os, re, sys, textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INIT = os.path.join(ROOT, 'parallel_bleeding_edge', 'src', 'init.f')
OUT  = os.path.join(ROOT, 'docs', 'source', 'reference', 'sph_input.rst')

def rst_escape(text):
    """Comments in init.f contain characters RST treats as markup.

    ``|`` starts a substitution reference and ``*`` starts emphasis, so a
    comment such as ``dt2=cn2*(h/|a-a_smoothed|)^0.5`` would otherwise break
    the build.  Escape them rather than reformatting the comment, so the page
    shows exactly what the source says.
    """
    for ch in ('\\', '|', '*', '`', '_'):
        text = text.replace(ch, '\\' + ch)
    return text


def is_comment(line):
    """Fixed-form Fortran: a comment marker must sit in column 1."""
    return (not line.strip()) or line[0] in 'cC*!'

def parse(path):
    lines = open(path, errors='ignore').read().split('\n')

    members, grabbing = [], False
    for l in lines:
        if re.match(r'\s+namelist/input/', l):
            grabbing = True
        elif grabbing and not re.match(r'\s{5}[$&]', l):
            grabbing = False
        if grabbing:
            l = re.sub(r'^\s+namelist/input/', '', re.sub(r'^\s{5}[$&]', '', l))
            members.append(l)
    members = [v.strip() for v in ','.join(members).split(',') if v.strip()]

    hi = next(i for i, l in enumerate(lines)
              if re.match(r"\s+open\(12,file='sph\.input'", l))
    lo = next(i for i in range(hi, 0, -1) if 'displacex=0d0' in lines[i])

    defaults = {}
    for l in lines[lo:hi]:
        if is_comment(l):
            continue
        m = re.match(r"\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^!]+?)\s*(?:!\s*(.*))?$", l)
        if m:
            defaults[m.group(1).lower()] = (m.group(2).strip(), (m.group(3) or '').strip())
    return members, defaults, lo + 1, hi

GROUPS = [
 ('Time and output', ['tf','dtout','nitpot','tjumpahead','tscanon','sepfinal','throwaway']),
 ('The particles',   ['n','nnopt','equalmass','starmass','starradius','hco','mco','hfloor']),
 ('Equation of state and physics',
                     ['neos','gam','nav','alpha','beta','ngr','nselfgravity','nkernel',
                      'ncooling','teq','reat']),
 ('Relaxation',      ['nrelax','trelax','treloff','tresplintmuoff','omega_spin']),
 ('Orbit of the encounter',
                     ['sep0','rp','impactparameter','e0','semimajoraxis','vinf2']),
 ('Compact object and black hole',
                     ['mbh','bbh_m1','bbh_m2','bbh_rp','bbh_semimajoraxis','bbh_vinf2',
                      'bbh_e0','bbh_trueanomaly','bbh_argperi','bbh_inclination',
                      'bbh_longitude']),
 ('Timestep control', ['nintvar','cn1','cn2','cn3','cn4','cn5','cn6','cn7']),
 ('Parallelism and GPUs',
                     ['ngravprocs','qthreads','ppn','computeexclusivemode','gflag']),
 ('Units',           ['runit','munit']),
 ('Input files',     ['startfile1','startfile2','eosfile','opacityfile','profilefile',
                      'stellarevolutioncodetype']),
]

def main():
    members, defaults, lo, hi = parse(INIT)
    placed = {v for _, vs in GROUPS for v in vs}
    leftover = [v for v in members if v.lower() not in placed]

    out = []
    w = out.append
    w('.. This page is generated by docs/generate_reference.py -- do not edit by hand.')
    w('')
    w('sph.input')
    w('=========')
    w('')
    w('Every run is controlled by a Fortran namelist in ``sph.input``.  A minimal file')
    w('sets only what it needs; anything omitted takes the default below.  The file')
    w('begins with ``&input`` and ends with ``&end``::')
    w('')
    w('    &input')
    w('     tf=200,')
    w('     n=20000,')
    w('    &end')
    w('')
    w('.. note::')
    w('')
    w('   The variables, defaults and descriptions on this page are read directly')
    w('   from ``parallel_bleeding_edge/src/init.f`` (lines %d-%d).  There are' % (lo, hi))
    w('   **%d** settings in the namelist.' % len(members))
    w('')

    def table(title, names):
        rows = [(n, defaults.get(n.lower(), ('--', ''))) for n in names
                if n.lower() in {m.lower() for m in members}]
        if not rows:
            return
        w(title); w('-' * len(title)); w('')
        w('.. list-table::')
        w('   :header-rows: 1')
        w('   :widths: 22 20 58')
        w('')
        w('   * - Variable'); w('     - Default'); w('     - Meaning')
        for n, (d, c) in rows:
            w('   * - ``%s``' % n)
            w('     - ``%s``' % d)
            w('     - %s' % (rst_escape(c) if c else
                             'See the discussion in the relevant tutorial.'))
        w('')

    for title, names in GROUPS:
        table(title, names)
    if leftover:
        table('Other settings', leftover)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').write('\n'.join(out) + '\n')
    print('wrote %s  (%d settings, %d ungrouped)' % (OUT, len(members), len(leftover)))

if __name__ == '__main__':
    main()
